name: Testy

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  unit-tests:
    name: Testy jednostkowe
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Instalacja zależności
        run: npm ci --legacy-peer-deps
      - name: Uruchomienie testów jednostkowych
        run: npm run test
      - name: Generowanie raportu pokrycia
        run: npm run test:coverage
      - name: Archiwizacja raportu pokrycia
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7

  e2e-tests:
    name: Testy E2E
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Instalacja zależności
        run: npm ci --legacy-peer-deps
      - name: Instalacja Playwright
        run: npx playwright install --with-deps chromium
      - name: Budowa aplikacji
        run: npm run build
      - name: Uruchomienie testów E2E
        run: npm run test:e2e
      - name: Archiwizacja wyników testów Playwright
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7 