name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      NODE_OPTIONS: "--max_old_space_size=8192"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Display Node and npm version
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Automatyczne formatowanie kodu
        run: |
          npm run format
        continue-on-error: true

      - name: Run linter on specific directories with auto-fix
        run: |
          npx eslint src/ --ext .js,.jsx,.ts,.tsx,.astro --fix --quiet --no-error-on-unmatched-pattern
        continue-on-error: true
      
      - name: Run unit tests
        run: npm run test
        
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install Playwright and dependencies
        run: |
          npx playwright install --with-deps chromium
        
      - name: Run e2e basic tests
        run: npm run test:e2e:basic
        continue-on-error: true

      - name: Clean temporary files
        run: |
          npm run clean:tmp || true
          rm -rf playwright-report || true
          rm -rf tmp || true
          
      - name: Build
        run: npm run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/
